services:
  uptime:
    image: shennarwp/uptime:alpine-latest
    container_name: uptime
    restart: always
    networks:
      - nginx
    environment:
      UPTIME_API_TOKEN: ${UPTIME_API_TOKEN}
      UPTIME_NTFY_URL: ${UPTIME_NTFY_URL:-}
    volumes:
      - ~/uptime/data:/app/data
    expose:
      - "80"

networks:
  nginx:
    external: true
