// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/targets": {
            "get": {
                "description": "Returns all monitored targets along with their most recent health checks (up to 1500 per target).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "targets"
                ],
                "summary": "List targets with recent checks",
                "responses": {
                    "200": {
                        "description": "List of targets with recent checks",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/database.TargetWithChecks"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "database.Check": {
            "type": "object",
            "properties": {
                "checked_at": {
                    "description": "CheckedAt is when the check was performed.",
                    "type": "string"
                },
                "error_message": {
                    "description": "ErrorMessage contains the error message when the check failed, if any.",
                    "type": "string"
                },
                "id": {
                    "description": "ID is the unique identifier of the check.",
                    "type": "integer"
                },
                "is_up": {
                    "description": "IsUp indicates whether the target was reachable.",
                    "type": "boolean"
                },
                "response_time_ms": {
                    "description": "ResponseTimeMS is the response time in milliseconds, if any.",
                    "type": "integer"
                },
                "status_code": {
                    "description": "StatusCode is the HTTP status code returned by the endpoint, if any.",
                    "type": "integer"
                },
                "target_id": {
                    "description": "TargetID references the target this check belongs to.",
                    "type": "integer"
                }
            }
        },
        "database.TargetWithChecks": {
            "type": "object",
            "properties": {
                "checks": {
                    "description": "Checks contains the recent health check results for the target.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.Check"
                    }
                },
                "created_at": {
                    "description": "CreatedAt is when the target was created.",
                    "type": "string"
                },
                "id": {
                    "description": "ID is the unique identifier of the target.",
                    "type": "integer"
                },
                "name": {
                    "description": "Name is a human-readable label for the target.",
                    "type": "string"
                },
                "schedule": {
                    "description": "Schedule is the cron expression used for polling.",
                    "type": "string"
                },
                "updated_at": {
                    "description": "UpdatedAt is when the target was last updated.",
                    "type": "string"
                },
                "url": {
                    "description": "URL is the endpoint that is being monitored.",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:80",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Uptime Monitor API",
	Description:      "Lightweight self-hosted uptime monitoring application API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
