// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/verify": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Checks whether the presented bearer token is valid. Returns 200 when valid, 401 otherwise.",
                "tags": [
                    "auth"
                ],
                "summary": "Verify API token",
                "responses": {
                    "200": {
                        "description": "Token is valid"
                    },
                    "401": {
                        "description": "Token is invalid"
                    }
                }
            }
        },
        "/api/target/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates the name and schedule of an existing target.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "targets"
                ],
                "summary": "Update a target",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Target ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated target fields (name and schedule only)",
                        "name": "target",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.UpdateTargetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated target",
                        "schema": {
                            "$ref": "#/definitions/database.Target"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Target not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/targets": {
            "get": {
                "description": "Returns all monitored targets along with their most recent health checks (up to 1500 per target).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "targets"
                ],
                "summary": "List targets with recent checks",
                "responses": {
                    "200": {
                        "description": "List of targets with recent checks",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/database.TargetWithChecks"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "database.Check": {
            "type": "object",
            "properties": {
                "checked_at": {
                    "description": "CheckedAt is when the check was performed.",
                    "type": "string"
                },
                "error_message": {
                    "description": "ErrorMessage contains the error message when the check failed, if any.",
                    "type": "string"
                },
                "id": {
                    "description": "ID is the unique identifier of the check.",
                    "type": "integer"
                },
                "is_up": {
                    "description": "IsUp indicates whether the target was reachable.",
                    "type": "boolean"
                },
                "response_time_ms": {
                    "description": "ResponseTimeMS is the response time in milliseconds, if any.",
                    "type": "integer"
                },
                "status_code": {
                    "description": "StatusCode is the HTTP status code returned by the endpoint, if any.",
                    "type": "integer"
                },
                "target_id": {
                    "description": "TargetID references the target this check belongs to.",
                    "type": "integer"
                }
            }
        },
        "database.Target": {
            "type": "object",
            "properties": {
                "cert_expires_at": {
                    "description": "CertExpiresAt is the NotAfter time of the TLS certificate most recently\nobserved for the target, in RFC3339 (UTC). Nil for HTTP targets or before\nthe first check observes a certificate.",
                    "type": "string"
                },
                "created_at": {
                    "description": "CreatedAt is when the target was created.",
                    "type": "string"
                },
                "id": {
                    "description": "ID is the unique identifier of the target.",
                    "type": "integer"
                },
                "name": {
                    "description": "Name is a human-readable label for the target.",
                    "type": "string"
                },
                "schedule": {
                    "description": "Schedule is the cron expression used for polling.",
                    "type": "string"
                },
                "updated_at": {
                    "description": "UpdatedAt is when the target was last updated.",
                    "type": "string"
                },
                "url": {
                    "description": "URL is the endpoint that is being monitored.",
                    "type": "string"
                }
            }
        },
        "database.TargetWithChecks": {
            "type": "object",
            "properties": {
                "cert_expires_at": {
                    "description": "CertExpiresAt is the NotAfter time of the TLS certificate most recently\nobserved for the target, in RFC3339 (UTC). Nil for HTTP targets or before\nthe first check observes a certificate.",
                    "type": "string"
                },
                "checks": {
                    "description": "Checks contains the recent health check results for the target.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.Check"
                    }
                },
                "created_at": {
                    "description": "CreatedAt is when the target was created.",
                    "type": "string"
                },
                "id": {
                    "description": "ID is the unique identifier of the target.",
                    "type": "integer"
                },
                "name": {
                    "description": "Name is a human-readable label for the target.",
                    "type": "string"
                },
                "schedule": {
                    "description": "Schedule is the cron expression used for polling.",
                    "type": "string"
                },
                "updated_at": {
                    "description": "UpdatedAt is when the target was last updated.",
                    "type": "string"
                },
                "url": {
                    "description": "URL is the endpoint that is being monitored.",
                    "type": "string"
                }
            }
        },
        "handler.UpdateTargetRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "schedule": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:80",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Uptime Monitor API",
	Description:      "Lightweight self-hosted uptime monitoring application API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
