name: Test and Build

on:
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read
  pull-requests: write

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout to the branch
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

    - name: Dependency review
      uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294
      with:
        comment-summary-in-pr: always

    - name: Set up Go
      uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
      with:
        go-version: '1.26.5'

    - name: Test go
      uses: robherley/go-test-action@v1
      with:
        testArguments: '-coverprofile=coverage.txt ./...'

    - name: Setup Node
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
      with:
        node-version: 24.18.1

    - name: Install dependencies
      run: npm ci --ignore-scripts --no-audit --no-fund
      working-directory: ./web

    - name: Run Frontend Tests
      run: npm run test:coverage
      working-directory: ./web

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Build
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: npm run build
      working-directory: ./web
